project:
  type: website
  resources: 
    - "static/*"
  # post-render:
  #   - "cp -rnv static/ _site/static"

website:
  title: "James Turk"
  site-url: https://jamesturk.net/
  description: "James Turk's blog"
  open-graph: true
  navbar:
    right:
      - href: /about/
        text: About
      - href: /projects/
        text: Projects
      - icon: github
        href: https://github.com/jamesturk/
      - icon: mastodon
        href: https://mastodon.social/@jamesturk/
      - icon: envelope
        href: mailto:contact@jamesturk.net
      - icon: rss
        href: index.xml
  page-footer:
    center: 
      - text: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
format:
  html:
    favicon: /static/favicon.ico
    theme:
      light: lumen
      dark: solar
    css: static/styles.css
    fontsize: 1.1em
    linestretch: 1.7



